minor fixes + replace all usage of GEF Elf object with pyelftools
mahaloz/decomp2gef pull request #25
Opened 2022-01-20 09:03 UTC by caprinux

works on 64 bit and 32 bit binaries, still require some work to fully port from GEF Elf class to pyelftools

2022-01-20 14:07 UTC, caprinux commented
addresses #24

2022-01-20 17:47 UTC, mahaloz requested changes
This looks really good @caprinux. Few changes, and I need to verify the binaries on my machine as well, then I think we are good to go. Nice stuff.

2022-01-20 17:47 UTC, mahaloz commented on decomp2gef.py
> +        if not section: return
```suggestion
        if not section: 
            return 
```

2022-01-20 17:47 UTC, mahaloz commented on decomp2gef.py
> +        """
comments in the middle of functions should all be "#" instead of the multiline comment style.

2022-01-20 17:47 UTC, mahaloz commented on decomp2gef.py
> +            title = "decompuiler:{:s}:error".format(self.decompiler.name)
```suggestion
            title = "decompiler:{:s}:error".format(self.decompiler.name)
```
Lol you placed a 'u' in decompiler

2022-01-21 07:59 UTC, mahaloz approved these changes

2022-01-21 07:59 UTC, merged